### ISSUE TITLE
Can't Connect to Database

### ISSUE THREAD

**Issue by NaheelSalman** [sazanrjb/InventoryManagementSystem#7]
I have created Database , As well setup the project with jdbc
but still it can't connect with mysql server
i have tried using 
user4, test123 or Test123
but failed to connect and get this error in my console screen:
`java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:923)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:404)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:317)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.inventory.database.ConnectionFactory.<init>(ConnectionFactory.java:26)
	at com.inventory.ui.LoginDialog.loginBttnMouseClicked(LoginDialog.java:193)
	at com.inventory.ui.LoginDialog.access$1(LoginDialog.java:187)
	at com.inventory.ui.LoginDialog$2.mouseClicked(LoginDialog.java:68)`

![dd](https://user-images.githubusercontent.com/39267623/98092040-06a8d900-1ea8-11eb-931c-c189ab720251.JPG)
![asd](https://user-images.githubusercontent.com/39267623/98092063-0dcfe700-1ea8-11eb-9db2-695fbaa98968.JPG)

**Comment by NaheelSalman** [comment]
Solution of jbdc Error Log:
here are two links
first read this article if you want concepts [Click Here](https://stackoverflow.com/questions/50387952/how-to-resolve-unable-to-load-authentication-plugin-caching-sha2-password-issu)
then go and download this jar file and extract your mysql java connector on your environment [Click Here](https://jar-download.com/download-handling.php)

**Comment by NaheelSalman** [comment]
Finally i got error and
You have used MD5 encryption method and the password stored in hashed form for test123 in ims.sql is wrong
its **'cc03e747a6afbbcbf8be7668acfebee5' = test123**
i'm going to fork that issue

**Comment by sajxraj** [comment]
Hi NaheelSalman,

Glad that you have solved the issue. Frankly speaking, this project was
done in my college days and I do not maintain it. The reason I did not dig
into the issue is I need to set up everything from scratch as I don't do
Java nowadays. However, if you have any fixes or ideas, you can contribute
to this project.

Many thanks,
Sajan Rajbhandari

**Comment by sajxraj** [comment]
Just out of curiosity though, what are you using this application for?

**Comment by NaheelSalman** [comment]
Welcome well i m collecting some demos to show to my sir for management systems for that i used it 
obviously i can't code from scratch if i have ability to read others code :)
and i appreciate your work ! 🥇
